version: '3.5'

services:
  production:
    build:
      context: .
      target: production
      args:
        APP_URL: https://gomoku-boardgame-io.herokuapp.com/
        FIREBASE_CONFIG: eyJhcGlLZXkiOiJBSXphU3lDSWlGZGZ2ZS1zdFpzTkE3OFhwZWFsNHdCeVVtZTktS3ciLCJhdXRoRG9tYWluIjoiZ29tb2t1LWJvYXJkZ2FtZS1pby5maXJlYmFzZWFwcC5jb20iLCJkYXRhYmFzZVVSTCI6Imh0dHBzOi8vZ29tb2t1LWJvYXJkZ2FtZS1pby5maXJlYmFzZWlvLmNvbSIsInByb2plY3RJZCI6ImdvbW9rdS1ib2FyZGdhbWUtaW8iLCJzdG9yYWdlQnVja2V0IjoiZ29tb2t1LWJvYXJkZ2FtZS1pby5hcHBzcG90LmNvbSIsIm1lc3NhZ2luZ1NlbmRlcklkIjoiNzQ4MzEzNzU2Njc0IiwiYXBwSWQiOiIxOjc0ODMxMzc1NjY3NDp3ZWI6NTY2MGVlOWQ1YWY4MjEzYTEwNTMxYiJ9
    environment:
      ADMIN_CREDENTIALS: ${ADMIN_CREDENTIALS}
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres?sslmode=require
      PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
