version: '3.5'

services:
  client:
    build:
      context: .
      target: base
    command: yarn start
    ports:
      - 1234:1234
    volumes:
      - ./package.json:/app/package.json
      - ./src:/app/src
    environment:
      PARCEL_WORKERS: 1

  server:
    build:
      context: .
      target: base
    command: 'yarn serve'
    environment:
      ADMIN_CREDENTIALS: ${ADMIN_CREDENTIALS}
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres
      PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./package.json:/app/package.json
      - ./src:/app/src
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
