version: '3.5'

services:
  production:
    build:
      context: .
      target: production
    environment:
      ADMIN_CREDENTIALS: ${ADMIN_CREDENTIALS}
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres
      PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
